"""Add validations to HeroPower and Power models

Revision ID: 98166c206171
Revises: 3afc3529c5cf
Create Date: 2025-06-18 13:23:03.159549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98166c206171'
down_revision = '3afc3529c5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('strength',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
